### ISSUE TITLE
Ability to inject custom parameters into objects constructed by TemplateFactories

### ISSUE THREAD

**Issue by emiax** [OpenSpace/Ghoul#10]
Something to possibly consider in the future.

Problem: Objects created by template factories require a default constructor or a Dictionary constructor. There is no way to pass in other/additional data/dependencies. 

### General example with possible new interface:

`FooBar` derives from `Foo`

`TemplateFactory<Foo> fooFactory = ...`
`fooFactory->registerClass<FooBar, StaticParam1Type, ..., StaticParamNType>("FooBar", staticParam1, ..., staticParamN);`

`fooFactory->create<DynamicParam1Type, ..., DynamicParamNType>("FooBar", dynamicParam1, ..., dynamicParamN);`
yields:
`std::make_unique<FooBar>(staticParam1, ..., staticParamN, dynamicParam1, ..., dynamicParamN);`

### More concrete example with dynamic params:
Passing in individual working directories to renderables, instead of fetching global working directory in constructor/init-method. (using dynamic params)

`renderableFactory->registerClass<RenderablePlanet>("RenderablePlanet"); // no static params`
`// and more classes`
`renderableFactory->create<Dictionary, std::string>(renerableTypeFromModFile, dictionaryFromModFile, filePath);`
yields:
`std::make_unique<RenderablePlanet>(dictionaryFromModFile, filePath);`

This would mean that template factory would not depend on Dictionary anymore. Instead, dictionaries could be passed in as dynamic parameters.

### Example with static params:
 Injecting the same TileCache pointer into TileProvider objects from the GlobeBrowsingModule, instead of accessing a singleton from the TileProvider. (using static params)

`tileProviderFactory->registerClass<TileProvider, TileCache*>("Temporal", tileCache);`
`// and more classes`
`tileProviderFactory->create<Dictionary>(tileProviderName, dictionary);`
yields:
`std::make_unique<TemporalTileProvider>(tileCache, dictionaryFromModFile);`

Not sure of:
1) how feasible it is to implement this, except that variadic templates would have to be a key ingredient.
2) if there are pitfalls in terms of added complexity or potentially confusing compile errors for developers.

**Comment by emiax** [comment]
Thinking about this a little bit more, the static params could be replaced with this kind of mechanism:

```
TemplateFactory<Foo> fooFactory = fooFactory->registerClass<FooBar>("FooBar", [](FooBar* ptr) {
    ptr->setSomeState(...);
});
```

**Comment by alexanderbock** [comment]
Maybe I think a combination of the two methods (variadic templates + initialize lambda) is necessary, though I would prefer if we can get away with only the variadic templates since a) it will be easier to reason about what happens in the constructor and b) there is no chance of creating a zombie object in case the lambda expression produces an error or exception
