### ISSUE TITLE
OpenSpace occasionally crashes with exception from ShaderObject::rebuildFromFile()

### ISSUE THREAD

**Issue by GPayne** [OpenSpace/Ghoul#17]
Frequency of this occurring is not high, but on an offsite installation it was crashing very frequently. I used RelWithDebInfo dump file to determine that an exception was being thrown from line 296 in shaderobject.cpp. Couldn't get finer detail than this from the dump file. This call is inside a #ifdef GHL_DEBUG section.
I re-built OpenSpace with the Ghoul CMake option GHOUL_HIGH_DEBUG_MODE disabled (which disabled GHL_DEBUG), and did not encounter this problem again, with a lot of successful re-runs of OpenSpace.

**Comment by GPayne** [comment]
Contents of log.html file after crash:
[crash_log.txt](https://github.com/OpenSpace/Ghoul/files/1163715/crash_log.txt)

**Comment by alexanderbock** [comment]
This is no longer a problem
