### ISSUE TITLE
TextureReader::loadTexture crashes if the load fails

### ISSUE THREAD

**Issue by GPayne** [OpenSpace/Ghoul#52]
`TextureReader::loadTexture(filename)` will throw a `MissingReaderException` exception if its load-from-file fails, but its sibling function `TextureReader::loadTexture(memory, size,  format)` will crash with an access to a nullptr if the load fails.

**Comment by Roxeena** [comment]
Fixed in 737419a8fd5b1da32924b86bcb243ec9a7834c62
