### ISSUE TITLE
Compilation fails

### ISSUE THREAD

**Issue by topiolli** [OpenSpace/Ghoul#77]
`include/ghould/lua/lua_helper.inl:262` calls `Name()` that has not been declared yet.

**Fix:** declare the `Name()` function before the `VariantName()` function.

The dependent type `T::value_type` appears multiple times without the `typename` keyword.

**Fix:** change `T::value_type` to `typename T::value_type`.

g++ (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0

**Comment by alexanderbock** [comment]
I forgot the check whether the change compiled on GCC, thanks for picking that up.    I pushed a change now that I managed to compile with exactly that version
